FROM python:3.6.8-slim

RUN python -m pip install --no-cache-dir \
    pip==21.3.1 \
    setuptools==59.6.0 \
    wheel==0.37.1

RUN python -m pip install --no-cache-dir \
    numpy==1.18.5 \
    scipy==1.4.1 \
    pandas==1.0.4 \
    statsmodels==0.11.0 \
    scikit-learn==0.23.1 \
    matplotlib==3.1.0 \
    seaborn==0.10.0

WORKDIR /work
